[package]
name = "rustc-hash"
version = "2.1.0"
authors = ["The Rust Project Developers"]
description = "A speedy, non-cryptographic hashing algorithm used by rustc"
license = "Apache-2.0 OR MIT"
readme = "README.md"
keywords = ["hash", "hasher", "fxhash", "rustc"]
repository = "https://github.com/rust-lang/rustc-hash"
edition = "2021"

[features]
default = ["std"]
std = []
nightly = []
rand = ["dep:rand", "std"]
rustc-dep-of-std = [
    "nightly",
    "std",
    "dep:core",
    "dep:std",
]

[dependencies]
rand = { version = "0.8", optional = true }
core = { version = "1", optional = true, package = "rustc-std-workspace-core" }
std = { version = "1", optional = true, package = "rustc-std-workspace-std" }
